# ======================================================================================
# Project metadata
# ======================================================================================

[project]
# Basic information
name = "gettsim"
dynamic = ["version"]
description = "The German Taxes and Transfers SIMulator"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
# About the project
authors = [
    { name = "Hans-Martin von Gaudecker", email = "hmgaudecker@uni-bonn.de" },
    { name = "Marvin Immesberger" },
    { name = "Christian Zimpelmann" }
]
maintainers = [
    { name = "Hans-Martin von Gaudecker", email = "hmgaudecker@uni-bonn.de" },
    { name = "Marvin Immesberger" }
]
keywords = [
    "Economics",
    "Taxes",
    "Benefits",
    "Transfers",
    "Pensions",
    "Germany",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
# Dependencies and requirements
requires-python = ">=3.11"
dependencies = [
    # "dags>=0.3.1",
    "ipywidgets",
    "networkx",
    "numpy",
    "numpy-groupies",
    "pandas",
    "openpyxl",
    "plotly>=6.2",
    "optree",
    "pygments",
    "pygraphviz",
    "pytest",
    "pyyaml",
]


[project.urls]
Repository = "https://github.com/iza-institute-of-labor-economics/gettsim"
Changelog = "https://gettsim.readthedocs.io/en/stable/changes.html"
Documentation = "https://gettsim.readthedocs.io"
Github = "https://github.com/iza-institute-of-labor-economics/gettsim"
Tracker = "https://github.com/iza-institute-of-labor-economics/gettsim/issues"


# ======================================================================================
# Build system configuration
# ======================================================================================

[build-system]
requires = ["hatchling", "hatch_vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.vcs]
version-file = "src/_gettsim/_version.py"

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
only-packages = true

[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = ["src"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.metadata]
allow-direct-references = true


# ======================================================================================
# Pixi
# ======================================================================================

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

# Development Dependencies (conda)
# --------------------------------------------------------------------------------------

[tool.pixi.dependencies]
python = ">=3.11,<3.14"
pre-commit = "*"
pandas = ">=2.2"
numpy_groupies = "*"
numpydoc = "*"
openpyxl = "*"
ipywidgets = "*"
jupyterlab = "*"
pygments = "*"
pygraphviz = "*"
pyyaml = "*"
toml = "*"
pytest = "*"
pytest-cov = "*"
pytest-profiling = "*"
pytest-xdist = "*"
snakeviz = ">=2.2.2,<3"


# Development Dependencies (pypi)
# --------------------------------------------------------------------------------------

[tool.pixi.pypi-dependencies]
gettsim = {path = ".", editable = true}
dags = { git = "https://github.com/OpenSourceEconomics/dags.git", branch = "main"}
jaxtyping = "*"
kaleido = ">=1.0"
pdbp = "*"


# Features
# --------------------------------------------------------------------------------------

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.jax.target.unix.dependencies]
jax = ">=0.6"
jaxlib = ">=0.6"

# [tool.pixi.feature.jax.pypi-dependencies]
# jax-datetime = { git = "https://github.com/google/jax-datetime.git" }

[tool.pixi.feature.jax.target.win-64.pypi-dependencies]
jax = { version = ">=0.6", extras = ["cpu"] }
jaxlib = ">=0.6"

[tool.pixi.feature.mypy.pypi-dependencies]
mypy = "~=1.16"
types-PyYAML = "*"
types-pytz = "*"

# Tasks
# --------------------------------------------------------------------------------------

[tool.pixi.feature.test.tasks]
tests = "pytest"

[tool.pixi.feature.jax.tasks]
tests-jax = "pytest --backend=jax"

[tool.pixi.feature.mypy.tasks]
mypy = "mypy --ignore-missing-imports"

# Environments
# --------------------------------------------------------------------------------------

[tool.pixi.environments]
mypy = ["mypy"]
py311 = ["test", "py311"]
py312 = ["test", "py312"]
py313 = ["test", "py313"]
py313-jax = ["py313", "test", "jax"]


# ======================================================================================
# Ruff configuration
# ======================================================================================

[tool.ruff]
target-version = "py311" # Replace by [project] requires-python = ">=3.11" above
fix = true
unsafe-fixes = false

[tool.ruff.lint]
select = ["ALL"]
extend-ignore = [
    "COM812", # Avoid conflicts with ruff-format
    "EM101", # Exception must not use a string literal
    "EM102", # Exception must not use an f-string literal
    "F722", # https://docs.kidger.site/jaxtyping/faq/#flake8-or-ruff-are-throwing-an-error
    "FBT001", # Boolean-typed positional argument in function definition
    "FBT002", # Boolean default positional argument in function definition
    "FIX002", # Line contains TODO -- Use stuff from TD area.
    "ICN001", # numpy should be np, but different convention here.
    "ISC001", # Avoid conflicts with ruff-format
    "N999", # Allow non-ASCII characters in file names.
    "PLC2401", # Allow non-ASCII characters in variable names.
    "PLC2403", # Allow non-ASCII function names for imports.
    "PLR0913", # Allow too many arguments in function definitions.
    "PLR5501", # elif not supported by vectorization converter for Jax
    "TRY003", # Avoid specifying long messages outside the exception class

    # Ignored during transition phase
    # ======================================
    "D", # docstrings
    "INP001", # implicit namespace packages without init.
    "PLR2004", # Magic values used in comparison
    "PT006", # Allows only lists of tuples in parametrize, even if single argument
    "PT007", # wrong type in parametrize
    "S101", # use of asserts outside of tests

]
exclude = []

[tool.ruff.lint.per-file-ignores]
"conftest.py" = ["ANN"]
"docs/**/*.ipynb" = ["T201"]
# Mostly things vectorization can't handle
"src/_gettsim/*" = ["E501", "PLR1714", "PLR1716", "E721", "SIM108", "RET"]
# All tests return None and use asserts
"src/_gettsim_tests/**/*.py" = ["ANN", "S101"]
"src/ttsim/interface_dag_elements/specialized_environment.py" = ["E501"]
"src/ttsim/interface_dag_elements/__init__.py" = ["TC"]
"src/ttsim/interface_dag_elements/fail_if.py" = ["E501"]
"src/ttsim/interface_dag_elements/typing.py" = ["PGH", "PLR", "SIM114"]
"src/ttsim/plot_dag.py" = ["FBT002"]
# Mostly things vectorization can't handle
"tests/ttsim/mettsim/**/*.py" = ["PLR1714", "PLR1716", "E721", "SIM108", "RET"]
"tests/ttsim/tt_dag_elements/test_vectorization.py" = ["PLR1714", "PLR1716", "E721", "SIM108", "RET"]
# All tests return None and use asserts
"tests/ttsim/**/*.py" = ["ANN", "S101"]
"tests/ttsim/interface_dag_elements/test_failures.py" = ["E501"]
# TODO: remove once ported nicely
"src/ttsim/stale_code_storage.py" = ["ALL"]
"outdated_docs/**/*.ipynb" = ["ALL"]
"src/_gettsim_tests/test_docs.py" = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"


# ======================================================================================
# mypy configuration
# ======================================================================================

[tool.mypy]
files = ["src", "tests"]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
explicit_package_bases = true
disallow_empty_bodies = false
disable_error_code = ["overload-cannot-match"]

[[tool.mypy.overrides]]
module = [
    "conftest",
    "src.ttsim.stale_code_storage",
    "src._gettsim_tests.test_docs",
]
disallow_untyped_defs = false
ignore_errors = true


[[tool.mypy.overrides]]
module = ["tests.*",]
disable_error_code = ["no-untyped-def"]  # All tests return None, don't clutter source code.

[[tool.mypy.overrides]]
module = ["src._gettsim_tests.*",]
disable_error_code = ["no-untyped-def"]  # All tests return None, don't clutter source code.

[tool.check-manifest]
ignore = ["src/_gettsim/_version.py"]


# ======================================================================================
# pytest configuration
# ======================================================================================

[tool.pytest.ini_options]
addopts = ["--pdbcls=pdbp:Pdb"]
filterwarnings = [
    "ignore:.*XMLParser*:DeprecationWarning",
    "ignore:.*'tree.iter()'*:PendingDeprecationWarning",
    "ignore:.*Sorting*:FutureWarning",
    "ignore:The TerminalReporter.writer attribute is",
    "ignore:Repeated execution of the test suite",
    "ignore:Using or importing the ABCs from 'collections'",
    "ignore:ttsim.interface_dag_elements.warn_if.FunctionsAndDataColumnsOverlapWarning"
]
markers = [
    "wip: Tests that are work-in-progress.",
    "unit: Flag for unit tests which target mainly a single function.",
    "integration: Flag for integration tests which may comprise of multiple unit tests.",
    "end_to_end: Flag for tests that cover the whole program.",
    "skipif_jax: skip test if backend is jax",
    "skipif_numpy: skip test if backend is numpy"
]
norecursedirs = ["docs"]
testpaths = [
    "src/_gettsim_tests",
    "tests/ttsim",
]

# ======================================================================================
# yamlfix configuration
# ======================================================================================

[tool.yamlfix]
line_length = 88
sequence_style = "block_style"
none_representation = "null"
