---
parameter_beitragssatz:
  name:
    de: Beitragssatz zur Arbeitslosenversicherung
    en: Unemployment insurance contribution rate.
  description:
    de: >-
      Beitragssatz zur Arbeitslosenversicherung, identisch für Arbeitnehmer und
      Arbeitgeber.
    en: >-
      Contribution rate to unemployment insurance, identical for employees and
      employers.
  unit: Share
  reference_period: null
  type: scalar
  access_different_date: jahresanfang
  1984-01-01:
    value: 0.023
  1985-01-01:
    value: 0.022
  1986-01-01:
    value: 0.0205
  1987-01-01:
    value: 0.0215
  1992-01-01:
    value: 0.0315
  1993-01-01:
    value: 0.0325
  1995-01-01:
    value: 0.0325
  1997-01-01:
    value: 0.0325
  2005-01-01:
    value: 0.0325
  2007-01-01:
    value: 0.021
  2008-01-01:
    value: 0.016
  2009-01-01:
    value: 0.014
  2011-01-01:
    value: 0.015
  2015-01-01:
    value: 0.015
  2019-01-01:
    value: 0.0125
    note: >-
      Set to 0.013 in Art. 2 Nr. 15 G. v. 18.12.2018 BGBl. I S. 2651. Temporarily
      reduced to 0.0125 in BeiSaV 2019.
    reference: V. v. 21.12.2018 BGBl. I S. 2663
  2020-01-01:
    value: 0.012
    note: Temporarily reduced to 0.012 in BeiSaV 2019.
    reference: V. v. 02.12.2019 BGBl. I S. 1998
  2023-01-01:
    value: 0.013
    note: >-
      Contribution rate was temporarily reduced from 2019 to 2022 in BeiSaV 2019. Back
      to level specified in § 341 Abs. 2 SGB III.
    reference: Art. 2 Nr. 15 G. v. 18.12.2018 BGBl. I S. 2651
